//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account_login.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class regi
    {
        public int id { get; set; }
        [Required(ErrorMessage ="This field is reqiured")]
        public string username { get; set; }
        [Required(ErrorMessage = "This field is reqiured")]
        [DataType(DataType.Password)]

        public string password { get; set; }
        [Required(ErrorMessage = "This field is reqiured")]
        [DataType(DataType.Password)]
        [DisplayName("confirmpassword")]
        public string confirmpassword { get; set; }
    }
}
